### ISSUE TITLE
Support for data (dzn) files

### ISSUE THREAD

**Issue by rtaupe** [siemens/JMiniZinc#12]
It shall be possible to specify values for non-instantiated constants in separate dzn files and pass them to the solver via an `Executor`.

**Comment by rtaupe** [comment]
On a related note, the diagnosis component currently also does not support models including parameters without values.

For example, if the model includes the statement `par bool: somepar;`, JMiniZinc will fail with the following exception:
```
java.lang.NullPointerException: Cannot invoke "String.equals(Object)" because "str" is null
	at at.siemens.ct.jmz.mznparser.MiniZincElementFactory.isBoolean(MiniZincElementFactory.java:156)
	at at.siemens.ct.jmz.mznparser.MiniZincElementFactory.getElementFromLine(MiniZincElementFactory.java:89)
	at at.siemens.ct.jmz.mznparser.MiniZincCP.parseMZN(MiniZincCP.java:51)
	at at.siemens.ct.jmz.mznparser.MiniZincCP.<init>(MiniZincCP.java:34)
	at at.siemens.ct.jmz.ui.VariableDialog.<init>(VariableDialog.java:62)
	at at.siemens.ct.jmz.ui.VariableDialog.main(VariableDialog.java:99)
```
